global:
  image: registry.hub.docker.com/library/node:16

  trigger:
    push:
      branches:
        - main

jobs:
  - name: install
    commands:
      - npm ci

  - name: build
    commands:
      - npm run build
    resources:
      - name: node_modules
        path: ./node_modules/
    artifacts:
      - name: build
        path: ./build/